"""Keyword rules for deterministic support email classification."""

from __future__ import annotations

CATEGORY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "billing": (
        "billing",
        "charged",
        "charge",
        "invoice",
        "payment",
        "refund",
        "receipt",
        "subscription",
        "price",
        "pricing",
        "card",
    ),
    "account": (
        "account",
        "login",
        "log in",
        "password",
        "reset",
        "locked",
        "mfa",
        "2fa",
        "verification",
        "email change",
    ),
    "bug": (
        "bug",
        "broken",
        "crash",
        "error",
        "exception",
        "fails",
        "failed",
        "not working",
        "blank screen",
        "timeout",
    ),
    "feature_request": (
        "feature",
        "could you add",
        "would like",
        "support for",
        "integration",
        "enhancement",
        "roadmap",
    ),
    "cancellation": (
        "cancel",
        "cancellation",
        "close my account",
        "delete my account",
        "unsubscribe",
        "stop billing",
    ),
    "sales": (
        "demo",
        "quote",
        "trial",
        "enterprise",
        "sales",
        "procurement",
        "contract",
        "purchase",
    ),
}

URGENCY_KEYWORDS: dict[str, tuple[str, ...]] = {
    "critical": (
        "security",
        "breach",
        "data loss",
        "production down",
        "cannot access",
        "all users",
        "outage",
    ),
    "high": (
        "urgent",
        "asap",
        "today",
        "blocked",
        "deadline",
        "escalate",
        "payroll",
        "customer waiting",
    ),
    "low": (
        "whenever",
        "minor",
        "suggestion",
        "nice to have",
        "no rush",
    ),
}
